# -*- coding: utf-8 -*-
"""bigmartSales_dataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XnzQ89mfEIbQrPttpfz5506kQNv8Q_Zg
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io
df = pd.read_csv(io.BytesIO(uploaded['bigmart.csv']))

df.head()
df.info()

df.isnull().sum()

df.describe()

df['Item_Weight'] = df.groupby('Item_Identifier')['Item_Weight'].transform(lambda x: x.fillna(x.mean()))
# then fallback for items with ALL missing:
df['Item_Weight'] = df.groupby('Item_Type')['Item_Weight'].transform(lambda x: x.fillna(x.mean()))

df['Outlet_Size'] = df['Outlet_Size'].fillna(
    df.groupby('Outlet_Type')['Outlet_Size'].transform(lambda x: x.mode()[0] if not x.mode().empty else np.nan)
)

fat_content_map = {
    'low fat': 'Low Fat',
    'LF': 'Low Fat',
    'reg': 'Regular',
    'regular': 'Regular'
}
df['Item_Fat_Content'] = df['Item_Fat_Content'].replace(fat_content_map)

import numpy as np
df['Item_Visibility'] = df['Item_Visibility'].replace(0, np.nan)
df['Item_Visibility'] = df['Item_Visibility'].fillna(df.groupby(['Item_Type','Outlet_Type'])['Item_Visibility'].transform('mean'))

dupe_check = df.groupby('Item_Identifier')['Item_Weight'].nunique()
print(f"Items with inconsistent weight: {(dupe_check > 1).sum()}")

raw = pd.read_csv(io.BytesIO(uploaded['bigmart.csv']))
raw_dupe_check = raw.groupby('Item_Identifier')['Item_Weight'].nunique(dropna=True)
print(f"Items with inconsistent non-null weight in RAW data: {(raw_dupe_check > 1).sum()}")

# Collapse each item to a single canonical weight (first occurrence)
canonical_weight = df.groupby('Item_Identifier')['Item_Weight'].transform('first')
df['Item_Weight'] = canonical_weight

df['Item_Weight'] = df.groupby('Item_Identifier')['Item_Weight'].transform('mean')

dupe_check = df.groupby('Item_Identifier')['Item_Weight'].nunique()
print(f"Items with inconsistent weight: {(dupe_check > 1).sum()}")

df.to_csv('cleaned_bigmart_data.csv', index=False)

check_df = pd.read_csv('cleaned_bigmart_data.csv')
print(f"Successfully saved! File shape: {check_df.shape}")